#include $(BR2_EXTERNAL_CUSTOM_RADXA_ZEROW_PATH)/package/package.mk
include $(BR2_EXTERNAL_CUSTOM_RADXA_ZEROW_PATH)/package/fip/fip.mk

export UBOOT_CUSTOM_REPO_VERSION:=$(BR2_TARGET_UBOOT_CUSTOM_REPO_VERSION)
